# NumPy Assignment

This assignment will help you practice working with NumPy arrays, including normalization, finding closest values, sorting, and array manipulation.

Make sure to import NumPy before starting!

In [1]:
import numpy as np

## Problem 1: Array Normalization

Create a 3x3 array with random integers between 1 and 100. Write a program to "normalize" the array so that the values are scaled between 0 and 1.

**Formula:** `(x - min) / (max - min)`

**Example Output:** An array where the smallest value becomes 0.0 and the largest becomes 1.0.

In [ ]:
rand_int_array = np.random.randint(1,101 , size=(3,3))
minimum = rand_int_array.min()
maximum = rand_int_array.max()
normalized_array = (rand_int_array - minimum) / (maximum - minimum)

print(normalized_array)

[[0.29885057 0.89655172 0.81609195]
 [0.91954023 0.85057471 0.        ]
 [0.3908046  0.10344828 1.        ]]


## Problem 2: Find Closest Value

Create a 1D array of 10 random numbers. Ask the user for a value X. Find the value in the array that is closest to X.

**Example Input:**
- Array: `[1, 5, 8, 12]`
- X = 10

**Example Output:** 8 or 12 (whichever is mathematically closer)

In [82]:
#I am assuming from the example  that numbers between 1 and 10 and integers
x= int(input("enter a number between 1 and 10: "))
array_ = np.random.randint(1,10,10)
print("array: ",array_)
array2= abs(x - array_)
closest_gap = array2.min()
closest_index = list(array2).index(closest_gap)
print("closest number: ", array_[closest_index])

enter a number between 1 and 10: 10
array:  [5 7 9 1 5 4 2 7 3 6]
closest number:  9


## Problem 3: Second-Largest Value in Each Column

Write a NumPy program to create a 5x5 array with random values. For each column in the array, find the second-largest value.

**Example Input:**
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

**Example Output:** `[4, 5, 6]` (These are the second-highest values for each respective column)

In [31]:
arr = np.random.randint(1,11,(5,5))
print("Array:\n", arr)

arr_sorted = np.sort(arr,axis=0)

second_highest= arr_sorted[-2]
print("second highest: " ,second_highest)

Array:
 [[ 3  8  7  3  5]
 [ 7  8  6  2 10]
 [ 2  8 10  2 10]
 [ 1  3  9  8  8]
 [ 7  5 10  1  2]]
second highest:  [ 7  8 10  3 10]


## Problem 4: Find Rows with Even Sum

Create a 6x4 matrix of random integers. Identify which rows have a sum that is an even number. Print the indices of these rows.

In [30]:
matrix=np.random.randint( 1,11,size = (6,4))
print("matrix:\n",matrix)
rows_sum = matrix.sum(axis=1)
print("sums: " ,rows_sum)
is_even = np.array(rows_sum%2 == 0)

indices= np.where(is_even) #we have not learned about it but I searched about a numpy method that returns an index
print(indices)


matrix:
 [[ 9  2  4  8]
 [ 4  1  7  4]
 [ 6  1  5  8]
 [ 3  6  1  1]
 [ 3  7  8  8]
 [ 8  7 10  3]]
sums:  [23 16 20 11 26 28]
(array([1, 2, 4, 5]),)


## Problem 5: Replace Multiples

Create a 1D array of 30 random integers between 1 and 50. Replace all numbers that are multiples of 3 or 5 with the value -1.

**Example Input:** `[3, 7, 10, 15]`

**Example Output:** `[-1, 7, -1, -1]`

In [17]:
arr = np.random.randint(1,51,size=30)
print("origin array: ",arr)
arr[arr%3==0 ] = -1
arr[arr%5==0] = -1
print("Replace Multiples array: ",arr)

origin array:  [33 43 25 50 45 49 10 32 31 30 34  5  4 21 16  6  9 20 11 42 18  9 42 16
  3  3  5 45 27 49]
Replace Multiples array:  [-1 43 -1 -1 -1 49 -1 32 31 -1 34 -1  4 -1 16 -1 -1 -1 11 -1 -1 -1 -1 16
 -1 -1 -1 -1 -1 49]


## Problem 6: Row Mean Subtraction

Write a NumPy program to create a 3x3 array with random values. For each row, calculate its mean (average) and subtract that mean from every element in that specific row.

**Example Input:**
```
[[10, 20, 30],
 [5, 5, 5],
 [0, 10, 20]]
```

**Example Output:**
```
[[-10.  0. 10.],
 [ 0.  0.  0.],
 [-10.  0. 10.]]
```

In [29]:
arr = np.random.randint(1,21,size=(3,3))
print("original array:\n",arr)
means = np.reshape(arr.mean(axis=1) , (3,1))
print("means array:\n",means)
print()
new_arr = arr - means
print("Row Mean Subtraction array:\n",new_arr)

original array:
 [[ 7 10 16]
 [ 4 19  1]
 [ 9  8  8]]
means array:
 [[11.        ]
 [ 8.        ]
 [ 8.33333333]]

Row Mean Subtraction array:
 [[-4.         -1.          5.        ]
 [-4.         11.         -7.        ]
 [ 0.66666667 -0.33333333 -0.33333333]]
